model_list:
  - model_name: "demo-model"
    litellm_params:
      model: "demo-provider/demo-model"

litellm_settings:
  custom_provider_map:
    - { "provider": "demo-provider", "custom_handler": demo_handler.demo_model }
